In [1]:
import math

In [2]:
math.sqrt(25)

5.0

In [4]:
math.pi

3.141592653589793

In [5]:
import math as mt

In [6]:
mt.sqrt(25)

5.0

In [7]:
from numpy import random

In [8]:
import numpy as np

In [9]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)

In [10]:
dataOne

array([[0.89410327, 0.52822982, 0.6622111 , 0.97644377, 0.36421524],
       [0.57785063, 0.71619237, 0.68788025, 0.00530581, 0.90327435],
       [0.82612718, 0.62704527, 0.27169535, 0.48287007, 0.98137149],
       [0.68325889, 0.99817166, 0.32646096, 0.90065604, 0.58551518],
       [0.04311563, 0.25907028, 0.02073858, 0.26484128, 0.22436697]])

In [11]:
np.mean(dataOne)

0.5524404569623231

In [12]:
add=np.add(dataOne,1)

In [13]:
add

array([[1.89410327, 1.52822982, 1.6622111 , 1.97644377, 1.36421524],
       [1.57785063, 1.71619237, 1.68788025, 1.00530581, 1.90327435],
       [1.82612718, 1.62704527, 1.27169535, 1.48287007, 1.98137149],
       [1.68325889, 1.99817166, 1.32646096, 1.90065604, 1.58551518],
       [1.04311563, 1.25907028, 1.02073858, 1.26484128, 1.22436697]])

In [14]:
np.maximum(dataOne)
#gave error: invalid number of arguments

ValueError: invalid number of arguments

In [15]:
np.amax(dataOne)

0.9981716560382036

In [16]:
round=np.around(dataOne)

In [17]:
round

array([[1., 1., 1., 1., 0.],
       [1., 1., 1., 0., 1.],
       [1., 1., 0., 0., 1.],
       [1., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.around(dataOne, decimals = 2)

array([[0.89, 0.53, 0.66, 0.98, 0.36],
       [0.58, 0.72, 0.69, 0.01, 0.9 ],
       [0.83, 0.63, 0.27, 0.48, 0.98],
       [0.68, 1.  , 0.33, 0.9 , 0.59],
       [0.04, 0.26, 0.02, 0.26, 0.22]])

In [19]:
np.median(dataOne)

0.5855151845136429

In [20]:
np.variance(dataOne)
#numpy has no attribute 'variance'

AttributeError: module 'numpy' has no attribute 'variance'

In [21]:
np.var(dataOne)

0.09474666183415177

In [22]:
np.std(dataOne)

0.3078094570252054

In [24]:
print('I love Data Science')

I love Data Science


In [25]:
variableName=25

In [26]:
variableName1='I Love data Science'

In [27]:
print(variableName1)

I Love data Science


In [28]:
type(variableName)

int

In [29]:
variableName=25.0

In [30]:
type(variableName)

float

In [31]:
varOne=25

In [32]:
varTwo=25.0

In [33]:
varThree=varOne+varTwo

In [34]:
print(varThree)

50.0


In [35]:
varOne=25

In [36]:
varTwo='Hello'

In [37]:
varThree=varOne+varTwo
#TypeError: unsupported operand type(s) for +: 'int' and 'str'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [38]:
listOne=[1, 2, 3, 4]

In [41]:
print(listOne[1:3])

[2, 3]


In [42]:
tel = {'jack': 4098, 'sape': 4139}

In [43]:
tel['jack']

4098

In [44]:
test={'eggs':3, 'guac':7, 'bread':2, 'bacon':5, 'salmon':15}

In [47]:
print(sorted(test))

['bacon', 'bread', 'eggs', 'guac', 'salmon']


In [53]:
np.add(test[0:1])

TypeError: unhashable type: 'slice'

In [54]:
np.add(test['eggs'], test['guac'])

10

In [56]:
np.multiply(test['bread'], 4)

8

In [59]:
total=sum(test.values())

In [60]:
np.subtract(total, test['salmon'])

17